### ISSUE TITLE
Copy-Pasted text doesnt show

### ISSUE THREAD

**Issue by BengMegma** [NoelleTGS/osu-bbcode-editor#3]
Copy Pasting the bbcode straight from your profile doesnt show in the editor.

![image](https://github.com/user-attachments/assets/53799bc8-7172-4449-8729-d0e0afb31ca0)

**Comment by NoelleTGS** [comment]
Does it show if you make any edits to the text?

**Comment by BengMegma** [comment]
Doesnt show when i edit the text (i added beans beans beans to the first line)
![image](https://github.com/user-attachments/assets/f1edeab4-76c2-4e7e-8c83-60c010bc81b8)

**Comment by BengMegma** [comment]
Should say, i am using Firefox.

**Comment by NoelleTGS** [comment]
I'll push a build with some better logging a little later. In the meantime, can you open up the dev tools menu with F12 and show me the output of the console tab?

**Comment by NoelleTGS** [comment]
I think I found your issue. Try with the latest build.

**Comment by BengMegma** [comment]
yep working now, thanks :D
