### ISSUE TITLE
Box icon does not reflect its actual state on content reparse

### ISSUE THREAD

**Issue by xayanide** [NoelleTGS/osu-bbcode-editor#5]
### Steps to reproduce
1. Go to https://noelletgs.github.io/osu-bbcode-editor (Commit https://github.com/NoelleTGS/osu-bbcode-editor/commit/8c2a73fabfb0afc5bffa9c6a4019a14d6211ca43 as of issue submission)
2. Paste this sample BBCode
```bbcode
[box=Example]
This is the content of the box labeled "Example."
[/box]
```
3. Open the box if is closed.
4. Modify the current BBCode on the left pane with anything you want, a simple whitespace will do.
For instance I will type the character `a` for the contents in the right pane to refresh.
```bbcode
[box=Example]
This is the content of the box labeled "Example."
[/box]a
```
### Expected behavior
Icon should reflect the box's state.

### Actual behavior
By default on how it was initially written it is open, but the icon does not reflect and retain its "opened" state.

### Relevant code worht mentioning in the repository
This is the most likely area the issue stems from.
https://github.com/NoelleTGS/osu-bbcode-editor/blob/8c2a73fabfb0afc5bffa9c6a4019a14d6211ca43/js/index.js#L179

**Comment by NoelleTGS** [comment]
I've known about this issue for a while but wasn't sure how to fix it at the time, just went back and it was easier than expected 😁 thank you for the report!
